title: "Michael Shawn Lockwood"
description: "SQL Server MCDBA | Performance | Automation"
logo: "/assets/images/profile.jpeg"
url: "https://michaelshawnlockwood.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  # - jekyll-paginate

remote_theme: mmistakes/minimal-mistakes

# Pick a built-in skin: default, air, aqua, contrast, dark, dirt, neon, plum
minimal_mistakes_skin: "dark"

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "assets/css/main.css"

  - scope:
      path: ""
      type: "posts"
    values:
      css: "assets/css/main.css"
      author_profile: true    # optional but nice (shows your profile sidebar)
      read_time: true         # optional (shows read time)
      share: true             # optional (share buttons)
      related: true           # optional (related posts)

# paginate: 5
# paginate_path: "/blog/page/:num/"
show_excerpts: true

header:
  image: /assets/images/headers/blog-hero.jpg
  image_description: "Abstract tech grid"
  teaser: /assets/images/headers/blog-hero.jpg




