title: My GitHub Pages Site
description: Built with Jekyll on GitHub Pages
baseurl: ""
url: "https://michaelshawnlockwood.github.io"

remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty
