title: "Michael Shawn Lockwood"
description: "SQL Server MCDBA | Performance | Automation"
logo: "/assets/images/profile.jpeg"
url: "https://michaelshawnlockwood.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

# Pick a built-in skin: default, air, aqua, contrast, dark, dirt, neon, plum
minimal_mistakes_skin: "dark"

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "assets/css/main.css"
