title: My GitHub Pages Site
description: Built with Jekyll on GitHub Pages
baseurl: ""
url: "https://michaelshawnlockwood.github.io"

plugins:
  - jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll

markdown: kramdown
permalink: pretty

navbar-links:
  About: "/#about"
  Skills: "/#skills"
  Experience: "/#experience"
  Projects: "/#projects"
  Writing: "/#writing"
  Contact: "/#contact"
