title: MSL.db
description: "Michael Shawn Lockwood"
plugins:
  - jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll
# Optional basic settings
navbar-links:
  About: "/#about"
  Skills: "/#skills"
  Experience: "/#experience"
  Projects: "/#projects"
  Writing: "/#writing"
  Contact: "/#contact"
