title: "Michael Shawn Lockwood"
description: "SQL Server MCDBA | Performance Specialist | Automation Expert"
logo: "/assets/images/profile.jpeg"
url: "https://michaelshawnlockwood.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
sass:
  style: compressed

remote_theme: mmistakes/minimal-mistakes

incremental: true

# Pick a built-in skin: default, air, aqua, contrast, dark, dirt, neon, plum
minimal_mistakes_skin: "dark"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author: michael_lockwood
      author_profile: true
      css: "assets/css/main.css"
      read_time: true
      share: false
      related: true
      header: 
        overlay_image: /assets/images/headers/default-header.png
        overlay_filter: 0.20

show_excerpts: true

header:
  image: /assets/images/headers/blog-hero.jpg
  image_description: "Abstract tech grid"
  teaser: /assets/images/headers/blog-hero.jpg

permalink: /:year/:month/:day/:slug.html

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2






