title: My GitHub Pages Site
description: Built with Jekyll on GitHub Pages
baseurl: ""
url: "https://michaelshawnlockwood.github.io"

layout: default

plugins:
  - jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll


markdown: kramdown
permalink: pretty
