title: My GitHub Pages Site
description: Built with Jekyll on GitHub Pages
baseurl: ""
url: "https://michaelshawnlockwood.github.io"

layout: default
plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty
