title: MSL.db
description: "Portfolio powered by Jekyll"
url: "https://michaelshawnlockwood.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
remote_theme: jeromelachaud/freelancer-theme

markdown: kramdown
permalink: pretty
